from django.urls import path
from . import views
from django.views.generic.base import TemplateView

urlpatterns = [
    path('', views.index, name="index"),
    path('vivi-tarantino', views.vivitara, name="vivitarantino"),
    path('kacy-black', views.kacy, name="kacyblack"),
    path('bella-bumzy', views.bum, name="bellabumzy"),
    path('sam-slayres', views.sam, name="samslayres"),
    path('lana-rhoades', views.lana, name="lanarhoades"),
    path('bhad-babie', views.bhad, name="bhadbabie"),
    path('mia-khalifa', views.mia, name="miakhalifa"),
    path('pia-mia', views.pia, name="piamia"),
    path('melisa-belle', views.meli, name="melisabelle"),
    path('baby-girl-stormy', views.stormy, name="babygirlstormy"),
    path('mia-malkova', views.malk, name="miamalkova"),
    path('sophie-dee', views.dee, name="sophiedee"),
    path('karma-rx', views.rx, name="karmarx"),
    path('jordyn-woods', views.woods, name="jordynwoods"),
    path('riley-reid', views.reid, name="rileyreid"),
    path('amber-rose', views.rose, name="amberrose"),
    path('lexi-belle', views.lexi, name="lexibelle"),
    path('katrina-jade', views.jade, name="katrinajade"),
    path('miss-katie', views.katie, name="misskatie"),
    path('rage-queen', views.rage, name="ragequeen"),
    path('1c347ab37a7e4167a84a44e1e6b51f27.txt',TemplateView.as_view(template_name="linkpage/1c347ab37a7e4167a84a44e1e6b51f27.txt", content_type="text/plain")),
    path('sonja-morgan', views.sonja, name="sonjamorgan"),
    path('blac-chyna', views.ch, name="blacchyna"),
    path('jem-wolfie', views.jm, name="jemwolfie"),
    path('natalie-monroe', views.nat, name="nataliemonroe"),
    path('belle-delphine', views.bel, name="belledelphine"),
    path('bella-thorne', views.th, name="bellathorne"),
    path('tana-mongeau', views.ana, name="tanamongeau"),
    path('kanricos', views.ka, name="kanricos"),
    path('megan-barton-hanson', views.megan, name="meganbartonhanson"),
    path('corinna-kopf', views.kopf, name="corinnakopf"),
    path('monica-huldt', views.mon, name="monicahuldt"),
    path('molly-eskam', views.esk, name="mollyeskam"),
    path('katelyn-runck', views.kate, name="katelynrunck"),
    path('sam-hickelspoon', views.sa, name="samhickelspoon"),
    path('haley-brooks', views.brooks, name="haleybrooks"),
    path('daisy-drew', views.daisy, name="daisydrew"),
    path('dana-dearmond', views.dana, name="danadearmond"),
    path('shady-doll', views.shady, name="shadydoll"),
    path('lucy-tisan', views.tisan, name="lucytisan"),
    path('lena-paul', views.paul, name="lenapaul"),
    path('adriana-chechik', views.adriana, name="adrianachechik"),
    path('kira-noir', views.noi, name="kiranoir"),
    path('honey-asian', views.ho, name="honeyasian"),
    path('paige-steele', views.pag, name="paigesteele"),
    path('jewelz-blu', views.blu, name="jewelzblu"),
    path('miss-kirroyal', views.ki, name="misskirroyal"),
    path('aisha', views.ai, name="aisha"),
    path('milkimind', views.mi, name="milkimind"),
    path('sasha-asian-vip', views.vip, name="sashaasianvip"),
    path('ittybittyprettykitty', views.bitt, name="ittybittyprettykitty"),
    path('thekatykat', views.kat, name="thekatykat"),
    path('samlypuff', views.sss, name="samlypuff"),
    path('pokebella', views.poke, name="pokebella"),
    path('nastyaa', views.nas, name="nastyaa"),
    path('jojolovesex', views.jojo, name="jojolovesex"),
    path('lenina-crowne', views.jo, name="leninacrowne"),
    path('lilybigboobs', views.lily, name="lilybigboobs"),
    path('polly-kendall', views.polly, name="pollykendall"),
    path('gemma-massey', views.gem, name="gemmamassey"),
    path('victoria-may', views.may, name="victoriamay"),
    path('kira-bee', views.bee, name="kirabee"),
    path('lauren-elizabeth', views.eze, name="laurenelizabeth"),
    path('tiny-vanessa', views.iny, name="tinyvanessa"),
    path('alyssa-macdonald', views.cd, name="alyssamacdonald"),
    path('lyricsbylyla', views.lyrics, name="lyricsbylyla"),
    path('profiles', views.pro, name="profiles"),

    
     ]


